[project]
name = "unify"
version = "0.1.0"
description = ""
authors = [
    {name = "the truth"}
]
license = {text = "MIT"}
requires-python = ">=3.11,<4.0"
dependencies = [
    "uvicorn (>=0.34.0,<0.35.0)",
    "fastapi[standard] (>=0.115.12,<0.116.0)",
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "motor (>=3.7.0,<4.0.0)",
    "pyjwt (>=2.10.1,<3.0.0)",
    "passlib (>=1.7.4,<2.0.0)",
    "argon2-cffi (>=23.1.0,<24.0.0)",
    "redis (>=5.2.1,<6.0.0)",
    "pytest (>=8.3.5,<9.0.0)",
    "pytest-asyncio (>=0.26.0,<0.27.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pymongo (>=4.13.0,<5.0.0)",
    "mongomock (>=4.3.0,<5.0.0)",
    "mongomock-motor (>=0.0.36,<0.0.37)",
    "pytest-mock (>=3.14.1,<4.0.0)",
    "testcontainers (>=4.10.0,<5.0.0)",
    "asgi-lifespan (>=2.1.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
